### ISSUE TITLE
Error when uploading large collection

### ISSUE THREAD

**Issue by jlkravitz** [qdrant/qdrant#5774]
Reposting a similar issue I posted on the Rust client repository, which continues to affect our team and which we suspect is an issue with QDrant and not the Rust client: https://github.com/qdrant/rust-client/issues/187

I am unable to upload a large collection of vectors without getting a timeout error.

## Current Behavior

I am uploading a collection of 385,186,142 vectors of dimension 512. Several million vectors into the upload, the upload stops with an error: "Error: Error in the response: The operation was cancelled Timeout expired."

If I try to delete and recreate the collection after this timeout error, creating the collection times out after deleting.

If I try to create the collection again, I get an error message indicating that "Collection data already exists at ./storage/collections/..."

## Steps to Reproduce

1.
2.
3.
4.

<details>
<summary>
Collection config
</summary>

```json
{
  "params": {
    "vectors": {
      "size": 512,
      "distance": "Cosine",
      "on_disk": true,
      "datatype": "float16"
    },
    "shard_number": 1,
    "replication_factor": 1,
    "write_consistency_factor": 1,
    "on_disk_payload": true
  },
  "hnsw_config": {
    "m": 16,
    "ef_construct": 100,
    "full_scan_threshold": 10000,
    "max_indexing_threads": 0,
    "on_disk": false
  },
  "optimizer_config": {
    "deleted_threshold": 0.2,
    "vacuum_min_vector_number": 1000,
    "default_segment_number": 0,
    "max_segment_size": null,
    "memmap_threshold": null,
    "indexing_threshold": 0,
    "flush_interval_sec": 5,
    "max_optimization_threads": null
  },
  "wal_config": {
    "wal_capacity_mb": 32,
    "wal_segments_ahead": 0
  },
  "quantization_config": null,
  "strict_mode_config": {
    "enabled": false
  }
}
```

</details>

## Expected Behavior

I should not get a timeout error uploading a collection (or should get a more informative error message).

I should also never be in a situation where I both cannot create a collection or delete it.

**Comment by generall** [comment]
Hey @jlkravitz, I assume you also upload payloads along with vectors, right? If so, it might be a known problem of timeouts during rocksdb compaction. It should be fixed in v1.13 by replacing rocksdb with custom storage

**Comment by jlkravitz** [comment]
@generall Ah got it. We are uploading an internal ID as part of the payload.

Do you have an ETA on v1.13? In the meantime, might there be a workaround?

**Comment by timvisee** [comment]
> Do you have an ETA on v1.13? In the meantime, might there be a workaround?

We aim to release it at the end of the week.

**Comment by jlkravitz** [comment]
Got it. Thanks, @timvisee! Any draft documentation on the custom storage you can share? I'm particularly wondering if it'll be plug-and-play or require more extensive configuration / set-up. We're on a bit of a timeline, so just trying to get ahead of any issues before v1.13's release. No worries if not- and regardless, thanks for your quick responses! Really appreciate it.

**Comment by jlkravitz** [comment]
@timvisee I upgraded and got further in the upload, but still get the error "Error: Error in the response: The operation was cancelled Timeout expired."

The qdrant server logs are below. The error seems to be caused by a failure to allocate memory, but there is plenty of memory available on the system, so that seems unlikely.

I am running the most recent version of qdrant and the rust qdrant-client.

Any insight?

```
2025-01-21T23:40:33.563441Z ERROR segment::segment::segment_ops: Segment "./storage/collections/gLM2_650M_embed_OMG/0/segments/0b0f0bf9-47ea-4e07-8981-5e48f5220db9" operation error: Service runtime error: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.565802Z ERROR collection::collection_manager::collection_updater: Update operation failed: Service internal error: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.935436Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.935466Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.935916Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.935945Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.936544Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.936571Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.937123Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.937150Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.937692Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.937719Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.938353Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.938381Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.938821Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.938847Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.939369Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.939395Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
2025-01-21T23:40:33.939917Z ERROR qdrant::startup: Panic backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>

2025-01-21T23:40:33.939942Z ERROR qdrant::startup: Panic occurred in file std/src/sys/pal/unix/stack_overflow.rs at line 196: failed to allocate an alternative stack: Cannot allocate memory (os error 12)
panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.12/src/blocking/client.rs:1047:38:
```
```

**Comment by timvisee** [comment]
Based on the errors it looks like it's coming from an internal HTTP client.

How large is your snapshot in terms of GBs, and how much memory does the machine have?

**Comment by jlkravitz** [comment]
We're uploading 800M vectors with a payload that contains an internal ID of ~30 characters. The input is in an HDF5 format, and is 776GB.

When I run the upload again on a new collection, the error happens much earlier, which implies a storage issue to me.

I'm not sure how that might be happening because the machine is high-powered: we have an additional 3TB in storage available, and the machine has 2TB of memory total.

This may be unrelated, but the first time I ran the upload again on a new collection, I got a slightly different error.

```
terminate called recursively
terminate called after throwing an instance of 'std::system_error'
./entrypoint.sh: line 25:     7 Aborted                 (core dumped) ./qdrant $@
```

I'll keep digging into our system to see if it's an issue on our end.

**Comment by jlkravitz** [comment]
@timvisee FYI, if helpful, the qdrant server now seems to be looping (tries to load, crashes, restarts, etc.). It finally finished a full reboot after 5ish attempts.

```
           _                 _
  __ _  __| |_ __ __ _ _ __ | |_
 / _` |/ _` | '__/ _` | '_ \| __|
| (_| | (_| | | | (_| | | | | |_
 \__, |\__,_|_|  \__,_|_| |_|\__|
    |_|

Version: 1.13.0, build: ffda0b90
Access web UI at http://localhost:6333/dashboard

2025-01-22T15:57:50.901384Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json
2025-01-22T15:57:50.940950Z  INFO storage::content_manager::toc: Loading collection: gLM2_650M_tokenized_ds_embeds__v2
2025-01-22T15:58:02.097648Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_tokenized_ds_embeds__v2: 0/3 (0%)
2025-01-22T15:58:02.232598Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_tokenized_ds_embeds__v2: 3/3 (100%)
2025-01-22T15:58:13.522045Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_tokenized_ds_embeds__v2: 0/3 (0%)
2025-01-22T15:58:13.647966Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_tokenized_ds_embeds__v2: 3/3 (100%)
2025-01-22T15:58:13.801082Z  INFO storage::content_manager::toc: Loading collection: gLM2_650M_UR50_tokenized_ds_embeds
2025-01-22T15:58:24.128114Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_UR50_tokenized_ds_embeds: 0/3 (0%)
2025-01-22T15:58:24.257278Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_UR50_tokenized_ds_embeds: 3/3 (100%)
2025-01-22T15:58:35.399038Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_UR50_tokenized_ds_embeds: 0/3 (0%)
2025-01-22T15:58:35.524795Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_UR50_tokenized_ds_embeds: 3/3 (100%)
2025-01-22T15:58:35.622770Z  INFO storage::content_manager::toc: Loading collection: clip
2025-01-22T15:58:36.297208Z  INFO collection::shards::local_shard: Recovering collection clip: 0/1 (0%)
2025-01-22T15:58:36.312943Z  INFO collection::shards::local_shard: Recovered collection clip: 1/1 (100%)
2025-01-22T15:58:36.314146Z  WARN storage::content_manager::toc: Collection config is not found in the collection directory: ./storage/collections/cds_genome_centroids_1024_100pct_test, skipping
2025-01-22T15:58:36.314161Z  INFO storage::content_manager::toc: Loading collection: gLM2_650M_embed_OMG2
2025-01-22T15:58:36.838485Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_embed_OMG2: 0/1 (0%)
2025-01-22T15:58:37.257693Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_embed_OMG2: 1/1 (100%)
2025-01-22T15:58:37.259547Z  INFO storage::content_manager::toc: Loading collection: gLM2_650M_embed_OMG_nopayload
2025-01-22T15:58:37.302087Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_embed_OMG_nopayload: 0/1 (0%)
2025-01-22T15:58:37.576627Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_embed_OMG_nopayload: 1/1 (100%)
2025-01-22T15:58:37.578881Z  INFO storage::content_manager::toc: Loading collection: gLM2_650M_embed_OMG
2025-01-22T15:59:20.747665Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_embed_OMG: 0/1 (0%)
2025-01-22T15:59:23.541267Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_embed_OMG: 1/1 (100%)
2025-01-22T15:59:23.552744Z  INFO storage::content_manager::toc: Loading collection: gLM2_650M_UR50_structure_clip_v3
2025-01-22T15:59:38.246927Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_UR50_structure_clip_v3: 0/3 (0%)
2025-01-22T15:59:38.340239Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_UR50_structure_clip_v3: 3/3 (100%)
2025-01-22T15:59:52.447839Z  INFO collection::shards::local_shard: Recovering collection gLM2_650M_UR50_structure_clip_v3: 0/3 (0%)
2025-01-22T15:59:52.531394Z  INFO collection::shards::local_shard: Recovered collection gLM2_650M_UR50_structure_clip_v3: 3/3 (100%)
2025-01-22T15:59:52.656709Z  INFO storage::content_manager::toc: Loading collection: esm2_t33_650M_UR50D_tokenized_ds_embeds__v3
2025-01-22T16:00:03.167239Z  INFO collection::shards::local_shard: Recovering collection esm2_t33_650M_UR50D_tokenized_ds_embeds__v3: 0/3 (0%)
2025-01-22T16:00:03.297504Z  INFO collection::shards::local_shard: Recovered collection esm2_t33_650M_UR50D_tokenized_ds_embeds__v3: 3/3 (100%)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
./entrypoint.sh: line 25:     7 Aborted                 (core dumped) ./qdrant $@
```

**Comment by jlkravitz** [comment]
@timvisee I moved two large (200+ GB) collections out of the qdrant storage folder, and I now seem to be able to upload the dataset without a problem. I can't say if this was an issue with qdrant (corrupted shards/collection?), or with our machine. Let me know if you want to dig in and want any additional info from me! Otherwise, we can close this issue.

**Comment by timvisee** [comment]
I'm a bit surprised by the error:

> ```
> terminate called after throwing an instance of 'std::system_error'
>   what():  Resource temporarily unavailable
> ./entrypoint.sh: line 25:     7 Aborted                 (core dumped) ./qdrant $@
> ```

Are you using some kind of networked or swappable storage by any chance? Could there be a temporary disconnect of some sort causing this, that we normally don't see with locally mounted storage?

**Comment by harievg** [comment]
i do get exact same issue and host machine has same amount of memory as similar to @jlkravitz.
did you solved it if yes how? can i have further insights about this issue. 

thanks

**Comment by CaoHoangTung** [comment]
I'm having same exact issue with the latest version (v1.13.6), running with Docker on an Amazon Linux EC2 instance.

**Comment by viebboy** [comment]
I can confirm here that issue still persists after trying v1.14

**Comment by YongWookHa** [comment]
Similar error occurs during bulk inserting large(approx. 500M points) collection.
```
2025-06-01T07:32:22.743212Z ERROR qdrant::startup: Panic backtrace: 
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
    
2025-06-01T07:32:22.743230Z ERROR qdrant::startup: Panic occurred in file library/std/src/sys/pal/unix/stack_overflow.rs at line 200: failed to set up alternative stack guard page: Cannot allocate memory (os error 12)    
panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-0.12.15/src/blocking/client.rs:1048:38:

thread panicked while processing panic. aborting.
```

I have inserted around 430M points. Now when I try puting several hundreds of points, then the panic error occurs.
Though there are more than 1TB of memory is available on the host machine. Storage is sufficient too.
There are no resource limitation for the Qdrant instance.

**Comment by rodion-m** [comment]
Hey, Qdrant team. We also faced the same issue. Are there any updates on solving it?
cc @generall @timvisee @agourlay @IvanPleshkov

**Comment by generall** [comment]
> Cannot allocate memory (os error 12)

This error might be also related to the number of mmaps open by process. Please check your system limits 

```
cat /proc/sys/vm/max_map_count
```

and compare it to the process mmap usage count

```
wc -l /proc/$(pidof qdrant)/maps
```

**Comment by IvanBiruk** [comment]
> > Cannot allocate memory (os error 12)
> 
> This error might be also related to the number of mmaps open by process. Please check your system limits
> 
> ```
> cat /proc/sys/vm/max_map_count
> ```
> 
> and compare it to the process mmap usage count
> 
> ```
> wc -l /proc/$(pidof qdrant)/maps
> ```

Thank you. It helped us resolve the issue
