### ISSUE TITLE
Degraded Search Quality (HNSW Index Rebuild Required)

### ISSUE THREAD

**Issue by eek** [qdrant/qdrant#7147]
### Description

Following the fixes in #7132, we started running search quality checks in our collections and found the results to be concerning.

When running the default **Search Quality** evaluation on the collection `text_transcript_sentences_hydrogen`, the precision score came back at **85.86%**.

Since we use `tenant_id`s, we repeated the evaluation using an **advanced search quality config**:

```json
{
  "limit": 100,
  "filter": {
    "must": [
      {
        "key": "library_id",
        "match": { "value": "b50d1d00688b766fc19ec8dc6a8a535d" }
      }
    ]
  },
  "timeout": 20
}
```

This time, the precision score dropped to:

```
[26/08/2025, 14:54:02] Mean precision@100 for collection: 0.597 ± 0.0541
```

This was unexpected - we anticipated an **increase** when filtering by `tenant_id` and 0% when `tenant_id` is not present.

All of our collections HNSW config is the following:

```
{
  "m": 0,
  "ef_construct": 200,
  "full_scan_threshold": 10000,
  "max_indexing_threads": 0,
  "on_disk": false,
  "payload_m": 32
}
```
---

### Further Analysis

We built a script to analyze more deeply:

* Retrieved the first 1000 points (via scrolling, no filters).
* Ran vector search on those points **with the `library_id` filter applied**.
* Results: only **34% of points** were found in the top 100 results.

* Same score regardless of `hnsw_ef: 64`, `128`, or `512`.
* Without the `library_id` filter, recall jumped to **89%**.
* With `params: { exact: true }`, recall was **100%**.

We also tried:

* Dropping the `library_id` index (same results).
* Re-creating the index (with and without `is_tenant: true`) - same results.

Our collection has **4,777,333 points**.

---

### Suspected Cause

This issue may stem from a past bug where we mistakenly added `"is_tenant": true` to both `library_id` and `chunk_id`.
Later, we removed `chunk_id`, but the HNSW index might still be affected.

---

### Cross-Checks

We tested on another collection (`4,595,593 points`):

With filter:

```json
{
  "limit": 10,
  "filter": {
    "must": [
      { "key": "library_id", "match": { "value": "b50d1d00688b766fc19ec8dc6a8a535d" } }
    ]
  },
  "params": { "hnsw_ef": 128 }
}
```

* Search quality: **0.505 ± 0.1774**

Without filter:

```json
{
  "limit": 10,
  "params": { "hnsw_ef": 128 }
}
```

* Search quality: **0%** (expected, since `library_id` is the only `is_tenant` index).

Via our script:

* `hnsw_ef: 64` → 79%
* `hnsw_ef: 128` → 79%
* With `exact` → 100%
* Without `library_id` → 0% (expected).

---

Third collection (previously stable):

* `hnsw_ef: 128` → 90% (without `library_id` filter, expected 0%).
* `hnsw_ef: 128` → 63% (with `library_id` filter, expected >90%).

---

### Expected Behavior

* **Without `library_id` filter**: precision should be **0%**.
* **With `library_id` filter**: precision should be **>90%**.

---

### Possible Solution

Is there a way to **force a full rebuild of the HNSW index**?
It seems that dropping/re-creating scalar indexes or toggling `is_tenant: true` does not refresh the underlying HNSW graph.

---

### Environment

* Version: **v1.15.4-dev**

---

later-edit:

We decided to force rebuild the HNSW by setting the config:

```erlang
PATCH /collections/text_transcript_chunks_hydrogen
{
  "hnsw_config": {
    "payload_m": 0
  }
}
```

then re-enable it:

```
PATCH /collections/text_transcript_chunks_hydrogen
{
  "hnsw_config": {
    "payload_m": 32
  }
}
```

Seems we have been presented with an INFO: 
```
2025-08-26T12:42:39.604070Z  INFO collection::update_handler: Can't notify optimizers, assume process is dead. Restart is required    
```

But all 16 CPUs are working, we will update after the collection moves back from `🟡 yellow` to `🟢 green` 

Ok, re-index finished, now Search Quality is `0.894 ± 0.1821` without library_id, and Search Quality with `library_id` went up to `0.9995 ± 0.0022`.

Even on the 2nd collection after we rebuild the index we went from `0.505 ± 0.1774` to `1 ± 0`

So indeed, the HNSW index was broken.

**Comment by eek** [comment]
From our point of view the **Expected Behaviour** is that the HNSW index should not have required a rebuild, especially since this issue also affected 2 collections that had no recent `is_tenant` configuration changes. (but I guess it was from the previous mismatched indexes?)

**Actual Resolution**: Temporarily adjusting the `payload_m` parameter (from 32 to 0, then back to 32) successfully triggered a rebuild and restored proper search quality across all affected collections. We also noticed that setting it to 0 then 32 back doesn't fully rebuild unless we set it to 0, wait for the collection to go from yellow to green then set it back to 32 ensures that the index is fully rebuilt.

## Monitoring & Prevention

We're implementing continuous Search Quality monitoring with daily precision tests alongside our existing consistency checks to detect similar issues early.


## Questions

Since this affected collections beyond those with `is_tenant` changes, could there be a broader issue with HNSW index corruption in multi-tenant configurations?

Do HNSW indexes naturally degrade over time in multi-tenant configurations? Would periodic index rebuilds be a recommended maintenance practice to ensure optimal search quality?

This issue can be closed.

**Comment by timvisee** [comment]
Thank you for the detailed report. That is very much appreciated!

Excuse my late reply, I'm afraid it got lost in my inbox. I hope this issue has already been fixed in recent Qdrant versions though I cannot confirm that.

> Is there a way to force a full rebuild of the HNSW index?
It seems that dropping/re-creating scalar indexes or toggling is_tenant: true does not refresh the underlying HNSW graph.

Correct

The best I can suggest for now is to change the HNSW config, like you did. When you do, please make sure all segments have been optimized before changing the setting back to what it should be.

> ```
> 2025-08-26T12:42:39.604070Z  INFO collection::update_handler: Can't notify optimizers, assume process is dead. Restart is required
> ```

This should not be a concern when changing the HNSW parameters like above.

> From our point of view the Expected Behaviour is that the HNSW index should not have required a rebuild, especially since this issue also affected 2 collections that had no recent is_tenant configuration changes. (but I guess it was from the previous mismatched indexes?)

Agreed. In fact, I don't expect is_tenant to affect it like this at all. It's more about placing data on disk in a way that allows efficient access.

> Since this affected collections beyond those with is_tenant changes, could there be a broader issue with HNSW index corruption in multi-tenant configurations?

> Do HNSW indexes naturally degrade over time in multi-tenant configurations? Would periodic index rebuilds be a recommended maintenance practice to ensure optimal search quality?

Possible, but I wouldn't expect it. I must admit I don't have a good answer to this yet.

Question: are you always using just one payload index filter? 

We did have some payload index bugs recently that might have stained the indices. Though then I'd also behave exact search to behave badly. If you feel adventurous you may: 1. upgrade to [v1.16.3](https://github.com/qdrant/qdrant/releases/tag/v1.16.3), and 2. recreate all payload indices (delete and create them). Though that'll definitely take some time.

Either way. Qdrant [1.15.0](https://github.com/qdrant/qdrant/releases/tag/v1.15.0)+ introduced some HNSW index changes including healing which should help keep recall high. I'll keep your report in mind for a bit and see if I can come up with a good explanation.

**Comment by eek** [comment]
## Update: Recurrence on v1.15.5 after heavy ingestion

Hey @timvisee, no worries about the late reply - and thanks for the detailed response back in December.

Unfortunately, the issue has recurred. We're still on **v1.15.5** (haven't upgraded yet) and after ingesting ~914K points in a single day into our `visual_helium` collection (from 7.82M to 8.74M points), the tenant HNSW subgraphs are broken again.

### Current state

```
Collection: visual_helium
Points: 8,737,161
Segments: 96
Shards: 12
Vectors: 1152d, Cosine
HNSW: m=0, payload_m=32, ef_construct=200
```

Payload schema (all indexes consistent this time - no missing points):

```json
{
  "library_id": { "data_type": "uuid", "params": { "type": "uuid", "is_tenant": true }, "points": 8736990 },
  "media_id": { "data_type": "uuid", "params": { "type": "uuid" }, "points": 8736990 },
  "folder_id": { "data_type": "uuid", "params": { "type": "uuid" }, "points": 8736990 }
}
```

### Search quality results

Using the Search Quality tool with tenant filter:

```json
{
  "limit": 10,
  "params": { "hnsw_ef": 128 },
  "filter": {
    "must": { "key": "library_id", "match": { "value": "b50d1d0069931d3abe15de962897c0d2" } }
  }
}
```

```
Mean precision@10: 0.2625 ± 0.1111
```

Individual results: `0.3, 0.4, 0.1, 0.3, 0.2, 0.4, 0.1, 0, 0, 0`

Even worse than the original report (which was `0.597 ± 0.0541` at precision@100).

### To answer your question

> Question: are you always using just one payload index filter?

Primarily `library_id` (our tenant filter), and sometimes `media_id` as an additional filter on top. The degraded search quality above was measured with `library_id` only.

### What we think is happening

The trigger seems to be heavy ingestion. Every time we do a large batch insert (~1M points in a day), the optimizer merges segments and the tenant HNSW subgraphs come out corrupted. The payload indexes themselves are fine (point counts match), but the HNSW graph built on top of them is broken. This is consistent with the original report where collections that had no `is_tenant` config changes were also affected - it's the segment optimization/merge cycle that corrupts the graph, not the index configuration itself.

### Our plan

1. **Immediate**: Rebuild the graph via the `payload_m=0` -> wait for green -> `payload_m=32` toggle 
2. **Upgrade**: We'll upgrade to **v1.16.3** as you recommended, skipping v1.17.0 for now (we'll wait for v1.17.1 to stabilize before jumping to that line)
3. **Monitor**: We'll report back over the next days/weeks after the upgrade to confirm whether the issue persists on v1.16.3 or if the payload index fixes there resolved it

Would be great to know if there's been any further insight into the root cause since December, or if v1.16.3 is expected to have addressed this.

**Comment by generall** [comment]
You can also try ACORN, but I would expect search quality to be OK for single filter as-is, tbh

**Comment by eek** [comment]
> You can also try ACORN, but I would expect search quality to be OK for single filter as-is, tbh

there's something broken. 

We did go to `payload_m=0` -> wait for green -> `payload_m=32` -> wait for green that previously would fix it, now on v1.15.5 it did not fix it.

We upgraded to v1.16.3 and did the above again, still broken.

Not only broken, but seems even worse, search quality fell to 0.

```
[25/02/2026, 14:26:46] Mean precision@10 for collection: NaN ± NaN
[25/02/2026, 14:26:46] Point ID 9(9/10) precision@10: 0 (search time exact: 1073ms, regular: 194ms)
[25/02/2026, 14:26:45] Point ID 8(8/10) precision@10: 0 (search time exact: 1109ms, regular: 197ms)
[25/02/2026, 14:26:43] Point ID 7(7/10) precision@10: 0 (search time exact: 1108ms, regular: 188ms)
[25/02/2026, 14:26:42] Point ID 6(6/10) precision@10: 0 (search time exact: 1136ms, regular: 199ms)
[25/02/2026, 14:26:41] Point ID 5(5/10) precision@10: 0 (search time exact: 1098ms, regular: 212ms)
[25/02/2026, 14:26:39] Point ID 4(4/10) precision@10: 0 (search time exact: 990ms, regular: 328ms)
[25/02/2026, 14:26:38] Point ID 3(3/10) precision@10: 0 (search time exact: 993ms, regular: 191ms)
[25/02/2026, 14:26:37] Point ID 2(2/10) precision@10: 0 (search time exact: 972ms, regular: 202ms)
[25/02/2026, 14:26:36] Point ID 1(1/10) precision@10: 0 (search time exact: 1102ms, regular: 307ms)
[25/02/2026, 14:26:34] Point ID 0(0/10) precision@10: 0 (search time exact: 1039ms, regular: 195ms)
[25/02/2026, 14:26:33] Starting measuring quality on 10 requests for 
```

Also, if I do a simple vector search now, all items come back with `score: null` which we've never seen before:

<img width="1243" height="1082" alt="Image" src="https://github.com/user-attachments/assets/35b1040c-6eb6-4a70-9932-29aa3f5a44b3" />

Both search quality and the above vector search are done with the tenant id filter:

```
  "filter": {
    "must": [
      {
        "key": "library_id",
        "match": {
          "value": "b50d1d0069931d3abe15de962897c0d2"
        }
      }
    ]
  }
```

Any suggestions?

PS: All the other collections are fine, only this one is dead. And not only that but only this particular mini-graph is dead. All the other library_ids from this collection are fine, just the one with `b50d1d0069931d3abe15de962897c0d2` is broken. This one is also one of the largest tenants within this collection (it might have even became the biggest one)

**Comment by eek** [comment]
Ok, so, we now upgraded to v1.17.0 and dropped the tenant id index, dropped payload m to 0, then re-added the index and re-added the payload_m to 32 so we re-trigger yet another graph build. (btw, nice optimization interface, we love it, a nice auto-refresh would be nice).

Unfortunately, search still doesn't work with this tenant id.

So, we made a script to scroll through the points to check if there's something wrong with the vectors themselves.

And we've spotted one point where the vector is all `null`, idk how it managed to bypass qdrant point upload check, it even crashed the sdk when I scrolled over it. 

<img width="1225" height="928" alt="Image" src="https://github.com/user-attachments/assets/6932b572-563c-42b2-ae58-a53ab835bb6f" />

I remember Qdrant errors any API call that has vectors with null in them, so it either managed to bypass the API validator, or somehow transformed to all `null`s afterwards 🤔 

<img width="1485" height="853" alt="Image" src="https://github.com/user-attachments/assets/27b1b640-6395-4b65-8edc-2b0422fdb832" />

Apparently 322 vector points with all `null` into them 🤔 after scrolling through this tenant which had 913,347 points

**Comment by eek** [comment]
hmm, seems it might be because we are using gRPC, which seems to allows us to add `NaN` / `None` vectors

**Comment by timvisee** [comment]
@eek the above is super weird. Vectors should not have null values. It is possible for a vector to not be set, but that still should not give back null values.

Do you still have a copy of the old version of the storage. And, would it be possible to share that with us (privately)? I'd be curious to see whether migrations are broken. But we don't have anything reproducable on our end just yet.

**Comment by eek** [comment]
Sure, I can give you something @timvisee, what exactly do you need? a snapshot from v1.15.5?

The biggest issues I think is the fact that we could upload null vectors in the database, easily replicable via gRPC. And from there the graph is corrupted. I don't think there are any issues with migrations, they just migrated what was already there (broken vectors).

Test script:
```
"""
Test: Upload a vector with NaN values to Qdrant, then retrieve it.
Does Qdrant store it? Does it come back as NaN or null?
"""

import numpy as np
from uuid import uuid4
from qdrant_client import QdrantClient
from qdrant_client.models import (
    PointStruct,
    VectorParams,
    Distance,
    HnswConfigDiff,
    UuidIndexParams,
    UuidIndexType,
)

client = QdrantClient(host="localhost", prefer_grpc=True)

COLLECTION = "visual_alpha"
VECTOR_SIZE = 1152

# Create test collection
if client.collection_exists(COLLECTION):
    client.delete_collection(COLLECTION)

client.create_collection(
    collection_name=COLLECTION,
    vectors_config=VectorParams(
        size=VECTOR_SIZE,
        distance=Distance.COSINE,
    ),
    hnsw_config=HnswConfigDiff(
        m=0,
        payload_m=32,
        ef_construct=200,
    ),
    on_disk_payload=True,
)

client.create_payload_index(
    collection_name=COLLECTION,
    field_name="library_id",
    field_schema=UuidIndexParams(
        type=UuidIndexType.UUID,
        is_tenant=True,
    ),
)

# Generate a random 1152-dim vector, then inject NaN at index 0
rng = np.random.default_rng(42)
embeddings = rng.standard_normal(VECTOR_SIZE).astype(np.float32)
embeddings[0] = float("nan")

print(f"Original vector[0:5]: {embeddings[0:5]}")
print(f"Has NaN: {np.any(np.isnan(embeddings))}")
print(f"NaN count: {np.sum(np.isnan(embeddings))}")

point_id = str(uuid4())
library_id = str(uuid4())
media_id = str(uuid4())

points = [
    PointStruct(
        id=point_id,
        vector=embeddings.tolist(),
        payload={
            "library_id": library_id,
            "media_id": media_id,
        },
    )
]

print(f"\nUploading point {point_id} with NaN vector...")
try:
    client.upload_points(
        points=points,
        collection_name=COLLECTION,
        parallel=1,
        max_retries=5,
        wait=True,
    )
    print("Upload succeeded!")
except Exception as e:
    print(f"Upload failed: {e}")
    # Try upsert instead
    print("\nTrying upsert...")
    try:
        client.upsert(collection_name=COLLECTION, points=points, wait=True)
        print("Upsert succeeded!")
    except Exception as e2:
        print(f"Upsert also failed: {e2}")
        exit(1)

# Retrieve it
print("\nRetrieving point...")
try:
    results = client.retrieve(
        collection_name=COLLECTION,
        ids=[point_id],
        with_vectors=True,
        with_payload=True,
    )
    if results:
        point = results[0]
        vec = point.vector
        print(f"Retrieved vector[0:5]: {vec[0:5] if vec else 'None'}")
        if vec:
            vec_arr = np.array(vec)
            print(f"Has NaN: {np.any(np.isnan(vec_arr))}")
            print(f"Has None: {any(v is None for v in vec)}")
            print(f"NaN count: {np.sum(np.isnan(vec_arr))}")
            print(f"Vector length: {len(vec)}")
        else:
            print("Vector is None!")
        print(f"Payload: {point.payload}")
    else:
        print("Point not found!")
except Exception as e:
    print(f"Retrieve failed: {e}")

# Also try via REST to see raw JSON
print("\n--- REST API check ---")
import httpx

resp = httpx.post(
    f"http://localhost:6333/collections/{COLLECTION}/points",
    json={"ids": [point_id], "with_vector": True, "with_payload": True},
)
print(f"Status: {resp.status_code}")
data = resp.json()
if data.get("result"):
    pt = data["result"][0]
    vec = pt.get("vector", [])
    print(f"REST vector[0:5]: {vec[0:5] if vec else 'None'}")
    if vec:
        nones = sum(1 for v in vec if v is None)
        print(f"None count in REST response: {nones}")
```

The test script successfully pushed a point with null vectors, then "theoretically" the whole HNSW graph gets corrupted on re-index.

**Comment by CakeWithDivinity** [comment]
We observe a similar issue on our qdrant.
The index quality (analyzed from the dashboard) is at around 0.4 for a snapshot taken from our production instance:
```
[3/10/2026, 7:47:58 PM] Mean precision@10 for collection: 0.4 ± 0.1414
[3/10/2026, 7:47:58 PM] Point ID 9(9/10) precision@10: 0.4 (search time exact: 9ms, regular: 4ms)
[3/10/2026, 7:47:58 PM] Point ID 8(8/10) precision@10: 0.3 (search time exact: 10ms, regular: 3ms)
[3/10/2026, 7:47:58 PM] Point ID 7(7/10) precision@10: 0.3 (search time exact: 10ms, regular: 3ms)
[3/10/2026, 7:47:58 PM] Point ID 6(6/10) precision@10: 0.3 (search time exact: 9ms, regular: 3ms)
[3/10/2026, 7:47:58 PM] Point ID 2(2/10) precision@10: 0.3 (search time exact: 10ms, regular: 3ms)
[3/10/2026, 7:47:58 PM] Point ID 1(1/10) precision@10: 0.5 (search time exact: 10ms, regular: 3ms)
[3/10/2026, 7:47:58 PM] Point ID 0(0/10) precision@10: 0.7 (search time exact: 10ms, regular: 3ms)
[3/10/2026, 7:47:58 PM] Starting measuring quality on 10 requests for Qwen/Qwen3-Embedding-4B
```
With a larger index quality analysis: `Mean precision@1000 for collection: 0.3445 ± 0.0245`
Also we have a tenant index on one of our uuid fields. With an index quality analysis with a filter set to the tenant index the results are equal 

Our hnsw config is similar:
```
// specifying vector field
{
  "m": 0,
  "payload_m": 16
}

// collection settings
{
  "m": 16,
  "ef_construct": 100,
  "full_scan_threshold": 10000,
  "max_indexing_threads": 0,
  "on_disk": false
}
```


The weird thing is that, when changing any parameter in the hnsw config even if you don't update the actual value behind it, the index quality goes to 100% instantly. However I would assume the same thing to happen initially because this is a snapshot from the production instance, which I upload locally and there shouldn't be anything regarding the index in there?

The collection contains around 25k points across 5 vectors with one of the vectors having `23523`. This is also the vector that we are analyzing and where the results are bad.

Unlike @eek however I cannot find any points with `null` in it's dimensions.

Is there anything you already found out or can I help with some additional data that might help you?
